fix -Werror=unused-value compile error
for detail
```
/home/baozhu/Arduino/libraries/DFRobot_ads1115/DFRobot_ADS1115.cpp: In member function 'bool DFRobot_ADS1115::checkADS1115()':
/home/baozhu/Arduino/libraries/DFRobot_ads1115/DFRobot_ADS1115.cpp:80:5: error: statement has no effect [-Werror=unused-value]
     ads_i2cAddress;
     ^~~~~~~~~~~~~~
/home/baozhu/Arduino/libraries/DFRobot_ads1115/DFRobot_ADS1115.cpp: In member function 'int16_t DFRobot_ADS1115::ComparatorVoltage(uint8_t)':
/home/baozhu/Arduino/libraries/DFRobot_ads1115/DFRobot_ADS1115.cpp:352:12: error: 'config' is used uninitialized in this function [-Werror=uninitialized]
     config |= ads_osmode;
     ~~~~~~~^~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```